import React from 'react';
import ReactDOM from 'react-dom';
import JsxFeature from './ES6/JsxFeature';
import List from './Component/List';
import Message from './Component/Message';
import List2 from './Component/List2';
import Counter from './Component/Counter';
import CounterProps1 from './Component_Parent_Child/CounterProps1';
import CounterProps2 from './Component_Parent_Child/CounterProps2';
import CounterProps3 from './Component_Parent_Child/CounterProps3';
import ComponentState from './Component_Parent_Child/ComponentState';
import InputRefString from './Component_Parent_Child/InputRefString';
import InputRefFunction from './Component_Parent_Child/InputRefFunction';
import InputRefCreateRef from './Component_Parent_Child/InputRefCreateRef';

// ReactDOM.render(<JsxFeature/>, document.getElementById('root') );
// ReactDOM.render(<List/>, document.getElementById('root') );
// ReactDOM.render(<Message/>, document.getElementById('root') );
// ReactDOM.render(<List2/>, document.getElementById('root') );
// ReactDOM.render(<Counter/>, document.getElementById('root') );
// ReactDOM.render(<CounterProps1 initCount={16} />, document.getElementById('root') );
// ReactDOM.render(<CounterProps2/>, document.getElementById('root') );
// ReactDOM.render(<CounterProps3 initCount={'5'}/>, document.getElementById('root') );
// ReactDOM.render(<ComponentState initCount={'5'}/>, document.getElementById('root') );
// ReactDOM.render(<InputRefString/>, document.getElementById('root') );
// ReactDOM.render(<InputRefFunction/>, document.getElementById('root') );
ReactDOM.render(<InputRefCreateRef/>, document.getElementById('root') );