import React from 'react';
import ReactDOM from 'react-dom';
import JsxFeature from './ES6/JsxFeature';
import List from './Component/List';
import Message from './Component/Message';
import List2 from './Component/List2';
import Counter from './Component/Counter';
import CounterProps1 from './Component_Parent_Child/CounterProps1';
import CounterProps2 from './Component_Parent_Child/CounterProps2';
import CounterProps3 from './Component_Parent_Child/CounterProps3';
import ComponentState from './Component_Parent_Child/ComponentState';
import InputRefString from './Component_Parent_Child/InputRefString';
import InputRefFunction from './Component_Parent_Child/InputRefFunction';
import InputRefCreateRef from './Component_Parent_Child/InputRefCreateRef';
import Parent from './Component_Parent_Child_Deliver/Parent';
import ParentTwo from './Component_Parent_Child_Deliver/ParentTwo';
import CtrlStyle from './Component_Parent_Child_Deliver/CtrlStyle';
import Progress from './Component_Parent_Child_Deliver/Progress';
import HocAppOne from './ComponentHoc/HocAppOne';
import HocAppTwo from './ComponentHocTwo/HocAppTwo';
import ListRendering from './ListRendering/ListRendering';
import ArrayFunction from './ListRendering/ArrayFunction';
import FormText from './Form/FormText';
import RadioCheckbox from './Form/RadioCheckbox';
import FileUpload from './Form/FileUpload';
import ComponentLifeCycle from './ComponentLifeCycle/ComponentLifeCycle';
import Profile from './ComponentLifeCycle/Profile';
import Render from './React16/Render';
import Lesson from './React16/Lesson';
import App_Context from './React16/Context/Before/AppContext';
import AppContext from './React16/Context/After/AppContext';
import UseStateApp from './Hooks/UseStateApp';
import UseStateApp2 from './Hooks/UseStateApp2';
import UseEffectApp from './Hooks/UseEffectApp';
import UseEffectApp2 from './Hooks/UseEffectApp2';
import UseFunOpen from './HooksUseContext/Before/UseFunOpen';
import UseContextOpen from './HooksUseContext/UseContextOpen';
import UseRefDom from './HooksUseRef/UseRefDom';
import UseRefFunctions from './HooksUseRef/UseRefFunctions';
import UseRefParent from './HooksUseRef/UseRefParent';
import TodoList from './HooksTodoList/TodoList';
import RouterDom from './Bootstrap/RouterApp/RouterDom';
import GridSystem from './Bootstrap/GridSystem';
import Components from './Bootstrap/Components';
import Carousels from './Bootstrap/Carousels';

ReactDOM.render(<JsxFeature/> ,document.getElementById('app'));
// ReactDOM.render(<List/> ,document.getElementById('app'));
// ReactDOM.render(<Message/> ,document.getElementById('app'));
// ReactDOM.render(<List2/> ,document.getElementById('app'));
// ReactDOM.render(<Counter/> ,document.getElementById('app'));
// ReactDOM.render(<CounterProps1 initCount={0} /> ,document.getElementById('app'));
// ReactDOM.render(<CounterProps2/> ,document.getElementById('app'));
// ReactDOM.render(<CounterProps3 initCount={'0'}/> ,document.getElementById('app'));
// ReactDOM.render(<ComponentState/> ,document.getElementById('app'));
// ReactDOM.render(<InputRefString/> ,document.getElementById('app'));
// ReactDOM.render(<InputRefFunction/> ,document.getElementById('app'));
// ReactDOM.render(<InputRefCreateRef/> ,document.getElementById('app'));
// ReactDOM.render(<Parent/> ,document.getElementById('app'));
// ReactDOM.render(<ParentTwo/> ,document.getElementById('app'));
// ReactDOM.render(<CtrlStyle/> ,document.getElementById('app'));
// ReactDOM.render(<Progress/> ,document.getElementById('app'));
// ReactDOM.render(<HocAppOne/> ,document.getElementById('app'));
// ReactDOM.render(<HocAppTwo/> ,document.getElementById('app'));
// ReactDOM.render(<ListRendering/> ,document.getElementById('app'));
// ReactDOM.render(<ArrayFunction/> ,document.getElementById('app'));
// ReactDOM.render(<FormText/> ,document.getElementById('app'));
// ReactDOM.render(<RadioCheckbox/> ,document.getElementById('app'));
// ReactDOM.render(<FileUpload/> ,document.getElementById('app'));
// ReactDOM.render(<ComponentLifeCycle/> ,document.getElementById('app'));
// ReactDOM.render(<Profile/> ,document.getElementById('app'));
// ReactDOM.render(<Render/> ,document.getElementById('app'));
// ReactDOM.render(<Lesson/> ,document.getElementById('app'));
// ReactDOM.render(<App_Context/> ,document.getElementById('app'));
// ReactDOM.render(<AppContext/> ,document.getElementById('app'));
// ReactDOM.render(<UseStateApp/> ,document.getElementById('app'));
// ReactDOM.render(<UseStateApp2/> ,document.getElementById('app'));
// ReactDOM.render(<UseEffectApp/> ,document.getElementById('app'));
// ReactDOM.render(<UseEffectApp2/> ,document.getElementById('app'));
// ReactDOM.render(<UseFunOpen/> ,document.getElementById('app'));
// ReactDOM.render(<UseContextOpen/> ,document.getElementById('app'));
// ReactDOM.render(<UseRefDom/> ,document.getElementById('app'));
// ReactDOM.render(<UseRefFunctions/> ,document.getElementById('app'));
// ReactDOM.render(<UseRefParent/> ,document.getElementById('app'));
// ReactDOM.render(<TodoList/> ,document.getElementById('app'));
// ReactDOM.render(<RouterDom/> ,document.getElementById('app'));
// ReactDOM.render(<GridSystem/> ,document.getElementById('app'));
// ReactDOM.render(<Components/> ,document.getElementById('app'));
// ReactDOM.render(<Carousels/> ,document.getElementById('app'));



