import React from 'react';
import ReactDOM from 'react-dom/client';
import JsxFeature from './ES6/JsxFeature';
import List from './Component/List';
import Message from './Component/Message';
import List2 from './Component/List2';
import Counter from './Component/Counter';
import CounterProps1 from './Component_Parent_Child/CounterProps1';
import CounterProps2 from './Component_Parent_Child/CounterProps2';
import CounterProps3 from './Component_Parent_Child/CounterProps3';
import ComponentState from './Component_Parent_Child/ComponentState';
import InputRefString from './Component_Parent_Child/InputRefString';
import InputRefFunction from './Component_Parent_Child/InputRefFunction';
import InputRefCreateRef from './Component_Parent_Child/InputRefCreateRef';
import Parent from './Component_Parent_Child_Deliver/Parent';
import ParentTwo from './Component_Parent_Child_Deliver/ParentTwo';
import CtrlStyle from './Component_Parent_Child_Deliver/CtrlStyle';
import Progress from './Component_Parent_Child_Deliver/Progress';
import HocAppOne from './ComponentHoc/HocAppOne';
import HocAppTwo from './ComponentHocTwo/HocAppTwo';
import HocAppThree from './ComponentHocThree/HocAppThree';
import ListRendering from './ListRendering/ListRendering';
import ArrayFunction from './ListRendering/ArrayFunction';
import FormText from './Form/FormText';
import RadioCheckbox from './Form/RadioCheckbox';
import FileUpload from './Form/FileUpload';
import ComponentLifeCycle from './ComponentLifeCycle/ComponentLifeCycle';
import Profile from './ComponentLifeCycle/Profile';
import Render from './React16/Render';
import Lesson from './React16/Lesson';
import App_Context from './React16/Context/Before/AppContext';
import AppContext from './React16/Context/After/AppContext';
import UseStateApp from './Hooks/UseStateApp';
import UseStateApp2 from './Hooks/UseStateApp2';
import UseEffectApp from './Hooks/UseEffectApp';
import UseEffectApp2 from './Hooks/UseEffectApp2';
import UseFunOpen from './HooksUseContext/Before/UseFunOpen';
import UseContextOpen from './HooksUseContext/UseContextOpen';
import UseRefDom from './HooksUseRef/UseRefDom';
import UseRefFunctions from './HooksUseRef/UseRefFunctions';
import UseRefParent from './HooksUseRef/UseRefParent';
import TodoList from './HooksTodoList/TodoList';
import RouterDom from './Bootstrap/RouterApp/RouterDom';
import GridSystem from './Bootstrap/GridSystem';
import Components from './Bootstrap/Components';
import Carousels from './Bootstrap/Carousels';
import SalesReport from './Homework/SalesReport';
import SalesReportSetState from './Homework/SalesReport_setState';
import SalesReportLifecycle from './Homework/SalesReport_Lifecycle';
import SalesReportHooks from './Homework/SalesReportHooks';

const root = ReactDOM.createRoot(document.getElementById('root'));

root.render(<JsxFeature/>);
// root.render(<List/>);
// root.render(<Message/>);
// root.render(<List2/>);
// root.render(<Counter/>);
// root.render(<CounterProps1 initCount={0} />);
// root.render(<CounterProps2/>);
// root.render(<CounterProps3 initCount={'0'}/>);
// root.render(<ComponentState/>);
// root.render(<InputRefString/>);
// root.render(<InputRefFunction/>);
// root.render(<InputRefCreateRef/>);
// root.render(<Parent/>);
// root.render(<ParentTwo/>);
// root.render(<CtrlStyle/>);
// root.render(<Progress/>);
// root.render(<HocAppOne/>);
// root.render(<HocAppTwo/>);
// root.render(<HocAppThree/>);
// root.render(<ListRendering/>);
// root.render(<ArrayFunction/>);
// root.render(<FormText/>);
// root.render(<RadioCheckbox/>);
// root.render(<FileUpload/>);
// root.render(<ComponentLifeCycle/>);
// root.render(<Profile/>);
// root.render(<Render/>);
// root.render(<Lesson/>);
// root.render(<App_Context/>);
// root.render(<AppContext/>);
// root.render(<UseStateApp/>);
// root.render(<UseStateApp2/>);
// root.render(<UseEffectApp/>);
// root.render(<UseEffectApp2/>);
// root.render(<UseFunOpen/>);
// root.render(<UseContextOpen/>);
// root.render(<UseRefDom/>);
// root.render(<UseRefFunctions/>);
// root.render(<UseRefParent/>);
// root.render(<TodoList/>);
// root.render(<RouterDom/>);
// root.render(<GridSystem/>);
// root.render(<Components/>);
// root.render(<Carousels/>);

// 購物網專題作業
// root.render(<SalesReport/>);
// root.render(<SalesReportSetState/>);
// root.render(<SalesReportLifecycle/>);
// root.render(<SalesReportHooks/>);



